import { FONTS, RADIUS } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

const createStyles = (COLORS: any) =>
    StyleSheet.create({
        content: {
            flex: 1,
            padding: 28,
            paddingBottom: 56,
            justifyContent: 'center',
        },
        artworkWrap: {
            marginTop: 20,
            alignItems: 'center',
        },
        artworkCard: {
            width: '84%',
            maxWidth: 320,
            aspectRatio: 1,
            borderRadius: RADIUS.lg,
            alignItems: 'center',
            justifyContent: 'center',
            overflow: 'hidden',
            // Enhanced purple glow
            shadowColor: COLORS.accent,
            shadowOffset: { width: 0, height: 0 },
            shadowOpacity: 0.45,
            shadowRadius: 40,
        },
        cycleBadge: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            marginBottom: 14,
            paddingVertical: 5,
            paddingHorizontal: 12,
            borderRadius: 20,
            borderWidth: 1,
        },
        cycleBadgeText: {
            fontSize: 11,
            fontFamily: FONTS.semibold,
            letterSpacing: 0.5,
        },
        timerValue: {
            fontSize: 54,
            fontFamily: FONTS.semibold,
            letterSpacing: -1,
            color: COLORS.text,
        },
        timerSubLabel: {
            marginTop: 2,
            fontSize: 10,
            fontFamily: FONTS.bold,
            letterSpacing: 1.2,
        },
        trackTitle: {
            marginTop: 20,
            fontSize: 22,
            fontFamily: FONTS.semibold,
            letterSpacing: -0.4,
            color: COLORS.text,
            textAlign: 'center',
        },
        trackMeta: {
            marginTop: 4,
            fontSize: 13,
            fontFamily: FONTS.regular,
            color: COLORS.neutral[500],
        },
        // Session-elapsed progress, not scrubbable — no touch handling.
        progressTrack: {
            marginTop: 18,
            width: '84%',
            maxWidth: 320,
            height: 4,
            borderRadius: 2,
            backgroundColor: COLORS.divider,
            overflow: 'hidden',
        },
        progressFill: {
            height: '100%',
            borderRadius: 2,
            backgroundColor: COLORS.accent,
        },
        cycleProgressRow: {
            flexDirection: 'row',
            gap: 12,
            marginTop: 18,
            width: '84%',
            maxWidth: 320,
        },
        cycleSegmentWrap: {
            flex: 1,
            gap: 4,
            alignItems: 'center',
        },
        cycleSegmentTrack: {
            width: '100%',
            height: 4,
            borderRadius: 2,
            backgroundColor: 'rgba(255, 255, 255, 0.08)',
            overflow: 'hidden',
        },
        cycleSegmentFill: {
            height: '100%',
            borderRadius: 2,
        },
        cycleSegmentText: {
            fontSize: 10.5,
            fontFamily: FONTS.medium,
            color: COLORS.neutral[500],
        },
        cycleSegmentTextActive: {
            color: COLORS.accent,
            fontFamily: FONTS.semibold,
        },
        transportRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 22,
            marginTop: 28,
            position: 'relative',
        },
        jumpButton: {
            width: 54,
            height: 54,
            borderRadius: 27,
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.08)',
            backgroundColor: 'rgba(26, 28, 44, 0.55)',
            alignItems: 'center',
            justifyContent: 'center',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 3 },
            shadowOpacity: 0.25,
            shadowRadius: 10,
        },
        jumpButtonDisabled: {
            borderColor: 'rgba(255, 255, 255, 0.03)',
            backgroundColor: 'rgba(26, 28, 44, 0.2)',
            opacity: 0.35,
        },
        playButton: {
            width: 72,
            height: 72,
            borderRadius: 36,
            backgroundColor: COLORS.accent,
            alignItems: 'center',
            justifyContent: 'center',
            shadowColor: COLORS.accent,
            shadowOffset: { width: 0, height: 0 },
            shadowOpacity: 0.5,
            shadowRadius: 28,
        },
        menuAnchor: {
            position: 'absolute',
            right: 0,
            top: 0,
            bottom: 0,
            justifyContent: 'center',
        },
        menuButton: {
            width: 40,
            height: 40,
            alignItems: 'center',
            justifyContent: 'center',
        },
        menuBackdrop: {
            position: 'absolute',
            top: -1000,
            bottom: -1000,
            left: -1000,
            right: -1000,
        },
        menu: {
            position: 'absolute',
            bottom: '100%',
            right: 0,
            marginBottom: 10,
            minWidth: 190,
            borderRadius: RADIUS.md,
            borderWidth: 1,
            borderColor: 'rgba(139,127,212,0.15)',
            backgroundColor: COLORS.surfaceElevated,
            paddingVertical: 6,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.35,
            shadowRadius: 16,
            elevation: 8,
        },
        menuRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 10,
            paddingVertical: 10,
            paddingHorizontal: 14,
        },
        menuRowLabel: {
            fontSize: 14,
            fontFamily: FONTS.medium,
            color: COLORS.neutral[300],
        },
        menuRowLabelActive: {
            color: COLORS.accent,
        },
    });

export default createStyles;
