import { StyleSheet } from 'react-native';
import { FONTS, RADIUS } from '@/src/constants/theme';

const createStyles = (COLORS: any) =>
    StyleSheet.create({
        content: {
            flex: 1,
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            paddingHorizontal: 28,
            paddingTop: 20,
        },
        title: {
            fontSize: 22,
            fontFamily: FONTS.semibold,
            letterSpacing: -0.4,
            color: COLORS.text,
        },
        closeButton: {
            width: 40,
            height: 40,
            borderRadius: 12,
            borderWidth: 1.5,
            borderColor: COLORS.divider,
            alignItems: 'center',
            justifyContent: 'center',
        },
        scroll: {
            paddingHorizontal: 20,
            paddingTop: 8,
            paddingBottom: 24,
        },
        stepBody: {
            flex: 1,
            paddingHorizontal: 20,
            paddingTop: 8,
        },
        activityBanner: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            marginTop: 12,
            marginBottom: 4,
            padding: 12,
            paddingHorizontal: 14,
            borderRadius: RADIUS.md,
            borderWidth: 1,
            borderColor: 'rgba(145, 132, 217, 0.2)',
            backgroundColor: 'rgba(26, 28, 44, 0.65)',
        },
        activityBannerIconBadge: {
            width: 32,
            height: 32,
            borderRadius: 16,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: 'rgba(145, 132, 217, 0.12)',
        },
        activityBannerTitle: {
            fontSize: 13,
            fontFamily: FONTS.semibold,
            color: COLORS.text,
        },
        activityBannerSubtitle: {
            fontSize: 11,
            fontFamily: FONTS.regular,
            color: COLORS.neutral[400],
            marginTop: 1,
        },
        timerTypeToggle: {
            flexDirection: 'row',
            gap: 8,
            marginTop: 20,
        },
        timerTypeButton: {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 9,
            borderRadius: RADIUS.md,
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.06)',
            backgroundColor: 'rgba(26, 28, 44, 0.4)',
        },
        timerTypeButtonActive: {
            borderColor: 'rgba(145, 132, 217, 0.35)',
            backgroundColor: 'rgba(145, 132, 217, 0.12)',
        },
        timerTypeButtonLabel: {
            fontSize: 12,
            fontFamily: FONTS.medium,
            color: COLORS.neutral[400],
        },
        timerTypeButtonLabelActive: {
            color: COLORS.text,
            fontFamily: FONTS.semibold,
        },
        rhythmRow: {
            flexDirection: 'row',
            gap: 8,
            marginTop: 12,
        },
        rhythmChip: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 5,
            paddingVertical: 7,
            borderRadius: RADIUS.sm + 2,
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.05)',
            backgroundColor: 'rgba(255, 255, 255, 0.02)',
        },
        rhythmChipActive: {
            borderColor: 'rgba(145, 132, 217, 0.35)',
            backgroundColor: 'rgba(145, 132, 217, 0.12)',
        },
        rhythmChipText: {
            fontSize: 11,
            fontFamily: FONTS.medium,
            color: COLORS.neutral[400],
        },
        rhythmChipTextActive: {
            color: COLORS.accent,
            fontFamily: FONTS.semibold,
        },
        sectionLabel: {
            marginTop: 20,
            fontSize: 11,
            fontFamily: FONTS.medium,
            letterSpacing: 1.4,
            color: COLORS.neutral[500],
        },
        selectedTrackCard: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            marginTop: 16,
            padding: 12,
            borderRadius: RADIUS.md,
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.06)',
            backgroundColor: 'rgba(26, 28, 44, 0.55)',
        },
        selectedTrackIcon: {
            width: 22,
            height: 22,
            alignItems: 'center',
            justifyContent: 'center',
        },
        selectedTrackTitle: {
            fontSize: 14,
            fontFamily: FONTS.medium,
            color: COLORS.text,
        },
        selectedTrackMeta: {
            marginTop: 2,
            fontSize: 12,
            fontFamily: FONTS.regular,
            color: COLORS.neutral[500],
        },
        durationGrid: {
            marginTop: 14,
            gap: 10,
        },
        durationGridRow: {
            flexDirection: 'row',
            gap: 10,
        },
        durationTile: {
            flex: 1,
            aspectRatio: 2.1,
            alignItems: 'center',
            justifyContent: 'center',
            gap: 3,
            borderRadius: RADIUS.md,
            borderWidth: 1,
            borderColor: 'rgba(139,127,212,0.1)',
            backgroundColor: COLORS.surfaceElevated,
        },
        durationTileActive: {
            borderColor: 'rgba(139,127,212,0.4)',
            backgroundColor: COLORS.accentTint,
        },
        durationTileValue: {
            fontSize: 28,
            fontFamily: FONTS.semibold,
            letterSpacing: -0.5,
            color: COLORS.text,
        },
        durationTileValueActive: {
            color: COLORS.accent,
        },
        durationTileUnit: {
            fontSize: 12,
            fontFamily: FONTS.medium,
            color: COLORS.neutral[400],
        },
        durationTileUnitActive: {
            color: COLORS.accent,
        },
        padWrap: {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
        },
        footer: {
            padding: 28,
            paddingTop: 12,
        },
        startButton: {
            paddingVertical: 16,
            borderRadius: RADIUS.md,
            backgroundColor: COLORS.accent,
            alignItems: 'center',
            justifyContent: 'center',
        },
        startButtonDisabled: {
            backgroundColor: COLORS.surfaceElevated,
            borderWidth: 1,
            borderColor: 'rgba(139,127,212,0.1)',
        },
        startButtonText: {
            fontSize: 15,
            fontFamily: FONTS.semibold,
            color: COLORS.bg,
        },
        startButtonTextDisabled: {
            color: COLORS.neutral[500],
        },
        secondaryButton: {
            marginTop: 12,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            paddingVertical: 15,
            borderRadius: RADIUS.md,
            borderWidth: 1,
            borderColor: 'rgba(139,127,212,0.15)',
        },
        secondaryButtonText: {
            fontSize: 14,
            fontFamily: FONTS.medium,
            color: COLORS.text,
        },
    });

export default createStyles;
